name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags
          token: ${{ secrets.GH_PUSH_PAT }}
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm ci
      - run: |
          # https://github.com/actions/checkout/pull/1184
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

          git fetch --all
          git checkout current
          git rebase ${{ github.ref }}

          npm run build
          lerna publish --no-private --exact --force-publish --yes $BUMP

          git push --force-with-lease
          git checkout next
          git rebase current
          git push --force-with-lease
        env:
          BUMP: ${{ github.event.inputs.bump }}
