name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm ci
      - run: |
          git fetch --all
          git checkout current
          git rebase ${{ github.ref }}
          npm run build
          lerna publish --no-private --exact --force-publish $BUMP
          git push
          git checkout next
          git rebase current
          git push
        env:
          BUMP: ${{ github.event.inputs.bump }}
